name: builder

on:
  workflow_dispatch:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@rosotest
        with:
          DEB_DISTRO: sid
          ROS_DISTRO: debian
          ROSDEP_SOURCE: yaml file:///home/runner/work/ros-one-packages/ros-one-packages/rosdep.yaml debian
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
