name: builder

on:
  workflow_dispatch:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-24.04
    steps:
      - uses: jspricke/ros-deb-builder-action@abng
        with:
          DEB_DISTRO: bookworm
          ROS_DISTRO: debian
          ROSDEP_SOURCE: yaml file:///home/runner/work/ros-one-packages/ros-one-packages/rosdep.yaml debian
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SBUILD_CONF: "$enable_network = 1;"
